/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;
import com.mycompany.escuela.AsistenciaDAO;
import java.sql.SQLException;
import java.util.List;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author JOVANNI SG
 */

public class Asistencia extends javax.swing.JFrame {

    /**
     * Creates new form Asistencia
     */
    Clase pantallaPrincipale; // Referencia a la Pantalla principal
    private int idGrupo;
    private List<Integer> idsAlumnos; // Lista de alumnos que recibimos
    private int currentIndex = 0; // Índice del alumno actual
    private ButtonGroup btnGroupAsistencia; // Grupo de botones de asistencia
    public Asistencia(int idGrupo, List<Integer> idsAlumnos) {
        this.idGrupo = idGrupo;
        this.idsAlumnos = idsAlumnos;

        initComponents();
        setTitle("Asistencia");
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        btnGroupAsistencia = new ButtonGroup(); // Inicializar el ButtonGroup
        btnGroupAsistencia.add(BotonPresente);
        btnGroupAsistencia.add(BotonNoPresente);

        mostrarAlumno(); // Mostrar el primer alumno al iniciar
    }
   // Método para mostrar al alumno actual
    private void mostrarAlumno() {
        if (currentIndex < idsAlumnos.size()) {
            int idAlumno = idsAlumnos.get(currentIndex);
            Grupo.setText("ID: " + idAlumno); // Asegúrate de tener un JLabel llamado lblAlumno para mostrar esto
        } else {
            JOptionPane.showMessageDialog(this, "Asistencia completada.", "Información", JOptionPane.INFORMATION_MESSAGE);
            dispose(); // Cierra la ventana cuando todos los alumnos hayan sido registrados
        }
    }

    // Método para guardar la asistencia en la base de datos
    private void guardarAsistencia(int asistencia) {
        try {
            int idAlumno = idsAlumnos.get(currentIndex);
            AsistenciaDAO asistenciaDAO = new AsistenciaDAO();
            asistenciaDAO.registrarAsistencia(idGrupo, idAlumno, asistencia);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al guardar asistencia: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Método para avanzar al siguiente alumno
    private void avanzarAlumno() {
        currentIndex++;
        mostrarAlumno(); // Mostrar al siguiente alumno
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Grupo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BotonPresente = new javax.swing.JRadioButton();
        BotonNoPresente = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nombrar Lista");

        Grupo.setBackground(new java.awt.Color(255, 255, 255));
        Grupo.setForeground(new java.awt.Color(0, 0, 0));
        Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Alumnos ");

        BotonPresente.setBackground(new java.awt.Color(255, 255, 255));
        BotonPresente.setForeground(new java.awt.Color(0, 0, 0));
        BotonPresente.setText("Presente");
        BotonPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonPresenteActionPerformed(evt);
            }
        });

        BotonNoPresente.setBackground(new java.awt.Color(255, 255, 255));
        BotonNoPresente.setForeground(new java.awt.Color(0, 0, 0));
        BotonNoPresente.setText("No presente");
        BotonNoPresente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNoPresenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonPresente, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BotonNoPresente)
                .addGap(0, 25, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(130, 130, 130))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonPresente)
                    .addComponent(BotonNoPresente))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonPresenteActionPerformed
        // TODO add your handling code here:
        guardarAsistencia(1); // Presente = 1
        avanzarAlumno(); // Avanzar al siguiente alumno
    }//GEN-LAST:event_BotonPresenteActionPerformed

    private void BotonNoPresenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNoPresenteActionPerformed
        // TODO add your handling code here:
        guardarAsistencia(0); // No Presente = 0
        avanzarAlumno(); // Avanzar al siguiente alumno
    }//GEN-LAST:event_BotonNoPresenteActionPerformed

    private void GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupoActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BotonNoPresente;
    private javax.swing.JRadioButton BotonPresente;
    private javax.swing.JTextField Grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
