/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.mycompany.escuela.EscuelaDAO;
import com.mycompany.escuela.Grupo;
import com.mycompany.escuela.GrupoDAO;
/**
 *
 * @author JOVANNI SG
 */
public class EliminarGrupo extends javax.swing.JFrame {

    /**
     * Creates new form EliminarGrupo
     */
    InicideClase pantallaPrincipale; // Referencia a la Pantalla principal
    private EscuelaDAO escuelaDAO; // Añadir la instancia de EscuelaDAO
    private GrupoDAO grupoDAO;
    public EliminarGrupo(InicideClase pantallas, EscuelaDAO escuelaDAO,GrupoDAO grupoDAO) {
         this.pantallaPrincipale = pantallas; // Se pasa la referencia a Pantalla principal
         this.escuelaDAO = escuelaDAO;
         this.grupoDAO = grupoDAO;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // o HIDE_ON_CLOSE según lo que necesites
        setTitle("NuevaEscuela");
        cargarEscuelasEnLista();
        ListadeEscuelas.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String escuelaSeleccionada = ListadeEscuelas.getSelectedValue();
            if (escuelaSeleccionada != null) {
                cargarDetallesGrupos(escuelaSeleccionada); // Carga los grupos según la escuela seleccionada
            }
        }
    });
    }
     private void cargarEscuelasEnLista() {
        try {
            List<String> nombresEscuelas = escuelaDAO.obtenerNombresEscuelas();
            DefaultListModel<String> model = new DefaultListModel<>();
            for (String nombre : nombresEscuelas) {
                model.addElement(nombre);
            }
            ListadeEscuelas.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las escuelas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
      private void cargarDetallesGrupos(String escuelaNombre) {
    try {
        List<String> detallesGrupos = grupoDAO.obtenerDetallesGruposPorEscuela(escuelaNombre);
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String detalle : detallesGrupos) {
            model.addElement(detalle);
        }
        ListadeClase.setModel(model); // Actualiza la lista de grupos en la interfaz
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los detalles de los grupos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadeEscuelas = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        botonBorrarActionPerformed = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListadeClase = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        idGrupoTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Footlight MT Light", 0, 18)); // NOI18N
        jLabel1.setText("Eliminar Grupo");

        jLabel2.setText("¿De que escuela es?");

        ListadeEscuelas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(ListadeEscuelas);

        jLabel3.setText("¿Que grupo es?");

        botonBorrarActionPerformed.setBackground(new java.awt.Color(153, 153, 153));
        botonBorrarActionPerformed.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        botonBorrarActionPerformed.setText("Borrar");
        botonBorrarActionPerformed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformedActionPerformed(evt);
            }
        });

        ListadeClase.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(ListadeClase);

        jLabel4.setText("Escriba la IdGrupo que quiera eliminar:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(102, 102, 102))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(botonBorrarActionPerformed)
                                .addContainerGap())))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(idGrupoTextField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idGrupoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(botonBorrarActionPerformed)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformedActionPerformed
    // Obtener el ID del grupo desde el JTextField
    String idGrupoTexto = idGrupoTextField.getText().trim();

    // Verificar si el campo está vacío
    if (idGrupoTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa un ID de grupo para eliminar.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int idGrupo = Integer.parseInt(idGrupoTexto);  // Convertir a entero

        // Verificar si el grupo existe en la base de datos
        if (grupoDAO.existeGrupo(idGrupo)) {
            // Eliminar el grupo
            grupoDAO.eliminarGrupo(idGrupo);
            JOptionPane.showMessageDialog(this, "Grupo eliminado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró un grupo con el ID proporcionado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El ID del grupo debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al eliminar el grupo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_botonBorrarActionPerformedActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListadeClase;
    private javax.swing.JList<String> ListadeEscuelas;
    private javax.swing.JButton botonBorrarActionPerformed;
    private javax.swing.JTextField idGrupoTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
