/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;
import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.mycompany.escuela.EscuelaDAO;
import com.mycompany.escuela.Grupo;
import com.mycompany.escuela.GrupoDAO;

/**
 *
 * @author JOVANNI SG
 */
public class GrupoNuevo extends javax.swing.JFrame {

    /**
     * Creates new form GrupoNuevo
     */
    InicideClase pantallaPrincipale; // Referencia a la Pantalla principal
    private EscuelaDAO escuelaDAO; // Añadir la instancia de EscuelaDAO
    public GrupoNuevo( InicideClase pantallas, EscuelaDAO escuelaDAO) {
         this.pantallaPrincipale = pantallas; // Se pasa la referencia a Pantalla principal
         this.escuelaDAO = escuelaDAO;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // o HIDE_ON_CLOSE según lo que necesites
        setTitle("NuevaEscuela");
        cargarEscuelasEnLista();
    }
    private void cargarEscuelasEnLista() {
        try {
            List<String> nombresEscuelas = escuelaDAO.obtenerNombresEscuelas();
            DefaultListModel<String> model = new DefaultListModel<>();
            for (String nombre : nombresEscuelas) {
                model.addElement(nombre);
            }
            ListadeEscuelas.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las escuelas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadeEscuelas = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        Grado = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        Grupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Matutino = new javax.swing.JRadioButton();
        Vespertino = new javax.swing.JRadioButton();
        AguardaGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Crear un Grupo");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¿Que escuela quieres?");

        ListadeEscuelas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        ListadeEscuelas.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(ListadeEscuelas);

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("¿Que Grado?");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("¿Que Grupo?");

        Grupo.setForeground(new java.awt.Color(0, 0, 0));
        Grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GrupoActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("¿Que Turno?");

        Matutino.setForeground(new java.awt.Color(0, 0, 0));
        Matutino.setText("Matutino");
        Matutino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatutinoActionPerformed(evt);
            }
        });

        Vespertino.setForeground(new java.awt.Color(0, 0, 0));
        Vespertino.setText("Vespertino");
        Vespertino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VespertinoActionPerformed(evt);
            }
        });

        AguardaGrupo.setBackground(new java.awt.Color(153, 153, 153));
        AguardaGrupo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AguardaGrupo.setForeground(new java.awt.Color(0, 0, 0));
        AguardaGrupo.setText("Aguarda");
        AguardaGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguardaGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AguardaGrupo)
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(30, 30, 30)))
                                .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(68, 68, 68)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Matutino))
                                .addComponent(Grado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Vespertino))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Grado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Matutino)
                    .addComponent(Vespertino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AguardaGrupo)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AguardaGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguardaGrupoActionPerformed
          // Obtener los valores de los campos de entrada
    String escuelaNombre = ListadeEscuelas.getSelectedValue();
    int grado = (int) Grado.getValue();
    String grupo = Grupo.getText();
    String turno = Matutino.isSelected() ? "Matutino" : "Vespertino";

    // Verificar que se haya seleccionado una escuela
    if (escuelaNombre == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una escuela.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Crear el objeto Grupo
    Grupo nuevoGrupo = new Grupo(0, String.valueOf(grado), grupo, turno, escuelaNombre);

    // Guardar el grupo en la base de datos usando GrupoDAO
    try {
        GrupoDAO grupoDAO = new GrupoDAO(); // Asegúrate de tener un constructor adecuado en GrupoDAO
        grupoDAO.guardarGrupo(nuevoGrupo);
        JOptionPane.showMessageDialog(this, "Grupo guardado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al guardar el grupo: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_AguardaGrupoActionPerformed

    private void MatutinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatutinoActionPerformed
        if (Matutino.isSelected()) {
        Vespertino.setEnabled(false);
    } else {
        Vespertino.setEnabled(true);
    }
    }//GEN-LAST:event_MatutinoActionPerformed

    private void VespertinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VespertinoActionPerformed
         if (Vespertino.isSelected()) {
        Matutino.setEnabled(false);
    } else {
        Matutino.setEnabled(true);
    }
    }//GEN-LAST:event_VespertinoActionPerformed

    private void GrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GrupoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GrupoActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AguardaGrupo;
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JSpinner Grado;
    private javax.swing.JTextField Grupo;
    private javax.swing.JList<String> ListadeEscuelas;
    private javax.swing.JRadioButton Matutino;
    private javax.swing.JRadioButton Vespertino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
