/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;
import com.mycompany.escuela.ActividadDAO;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JFrame;

/**
 *
 * @author Jovanni SG
 */
public class HistorialCalificasion extends javax.swing.JFrame {
    private ActividadDAO actividadDAO = new ActividadDAO();
    private DefaultListModel<String> modeloLista = new DefaultListModel<>();
    private int idGrupo; // Atributo para guardar el ID del grupo
    Clase pantallaPrincipale; // Referencia a la Pantalla principal
    /**
     * Creates new form HistorialCalificasion
     */
    public HistorialCalificasion(int idGrupo) {
         initComponents();
         mostrarEvaluaciones(idGrupo);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    private void mostrarEvaluaciones(int idGrupo) {
    DefaultListModel<String> modeloLista = new DefaultListModel<>();
    HistorialDeCalificasiones.setModel(modeloLista);
    
    ActividadDAO actividadDAO = new ActividadDAO();
    try {
        List<String> evaluaciones = actividadDAO.obtenerEvaluacionesPorGrupo(idGrupo);
        for (String evaluacion : evaluaciones) {
            modeloLista.addElement(evaluacion);
        }
    } catch (SQLException ex) {
        System.out.println("Error al obtener las evaluaciones: " + ex.getMessage());
    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CuadroHistorialCalificasion = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        HistorialDeCalificasiones = new javax.swing.JList<>();

        CuadroHistorialCalificasion.setBackground(new java.awt.Color(204, 204, 204));
        CuadroHistorialCalificasion.setColumns(20);
        CuadroHistorialCalificasion.setForeground(new java.awt.Color(255, 255, 255));
        CuadroHistorialCalificasion.setRows(5);
        jScrollPane1.setViewportView(CuadroHistorialCalificasion);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Historial de Actividad");

        HistorialDeCalificasiones.setBackground(new java.awt.Color(204, 204, 204));
        HistorialDeCalificasiones.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(HistorialDeCalificasiones);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea CuadroHistorialCalificasion;
    private javax.swing.JList<String> HistorialDeCalificasiones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
