/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;

import java.sql.SQLException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import com.mycompany.escuela.EscuelaDAO;
import com.mycompany.escuela.GrupoDAO;
import com.mycompany.escuela.AlumnoDAO;
import java.util.Scanner;

/**
 *
 * @author JOVANNI SG
 */
public class InicideClase extends javax.swing.JFrame {

    /**
     * Creates new form InicideClase
     */
    PantallaDeIncio pantallaPrincipale; // Referencia a la Pantalla principal
    private EscuelaDAO escuelaDAO; // Añadir la instancia de EscuelaDAO
    private GrupoDAO grupoDAO;
    public InicideClase(PantallaDeIncio pantallas, EscuelaDAO escuelaDAO,GrupoDAO grupoDAO) {
         this.pantallaPrincipale = pantallas; // Se pasa la referencia a Pantalla principal
         this.escuelaDAO = escuelaDAO;
         this.grupoDAO = grupoDAO;
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // o HIDE_ON_CLOSE según lo que necesites
        setTitle("NuevaEscuela");
        cargarEscuelasEnLista();
        //cargarDetallesGrupos();
        ListadeEscuelas.addListSelectionListener(e -> {
        if (!e.getValueIsAdjusting()) {
            String escuelaSeleccionada = ListadeEscuelas.getSelectedValue();
            if (escuelaSeleccionada != null) {
                cargarDetallesGrupos(escuelaSeleccionada); // Carga los grupos según la escuela seleccionada
            }
        }
    });
    }
     private void cargarEscuelasEnLista() {
        try {
            List<String> nombresEscuelas = escuelaDAO.obtenerNombresEscuelas();
            DefaultListModel<String> model = new DefaultListModel<>();
            for (String nombre : nombresEscuelas) {
                model.addElement(nombre);
            }
            ListadeEscuelas.setModel(model);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al cargar las escuelas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
     private void cargarDetallesGrupos(String escuelaNombre) {
    try {
        List<String> detallesGrupos = grupoDAO.obtenerDetallesGruposPorEscuela(escuelaNombre);
        
        DefaultListModel<String> model = new DefaultListModel<>();
        for (String detalle : detallesGrupos) {
            model.addElement(detalle);
        }
        ListadeClase.setModel(model); // Actualiza la lista de grupos en la interfaz
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error al cargar los detalles de los grupos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    String grupoSeleccionado = ListadeClase.getSelectedValue();
if (grupoSeleccionado != null) {
    // Suponiendo que el formato del grupo es "ID: 1 | Grupo: 3A Turno: Matutino"
    grupoSeleccionado = grupoSeleccionado.split("\\|")[1].trim().split(" ")[1]; // Extrae "3A"
}

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListadeEscuelas = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListadeClase = new javax.swing.JList<>();
        SiguienteClase = new javax.swing.JButton();
        EliminarClase = new javax.swing.JButton();
        NuevaClase = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(255, 0, 102));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("¿Que escuela quieres?");

        ListadeEscuelas.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jScrollPane1.setViewportView(ListadeEscuelas);

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("¿Que clase quieres?");

        ListadeClase.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jScrollPane2.setViewportView(ListadeClase);

        SiguienteClase.setBackground(new java.awt.Color(153, 153, 153));
        SiguienteClase.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        SiguienteClase.setForeground(new java.awt.Color(0, 0, 0));
        SiguienteClase.setText("Siguiente");
        SiguienteClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SiguienteClaseActionPerformed(evt);
            }
        });

        EliminarClase.setBackground(new java.awt.Color(153, 153, 153));
        EliminarClase.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        EliminarClase.setForeground(new java.awt.Color(0, 0, 0));
        EliminarClase.setText("Eliminar Clase");
        EliminarClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarClaseActionPerformed(evt);
            }
        });

        NuevaClase.setBackground(new java.awt.Color(153, 153, 153));
        NuevaClase.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        NuevaClase.setForeground(new java.awt.Color(0, 0, 0));
        NuevaClase.setText("Nueva Clase");
        NuevaClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SiguienteClase)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NuevaClase)
                        .addGap(18, 18, 18)
                        .addComponent(EliminarClase)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SiguienteClase)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevaClase)
                    .addComponent(EliminarClase))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NuevaClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaClaseActionPerformed
        // TODO add your handling code here:
        EscuelaDAO escuelaDAO = new EscuelaDAO();
        Scanner scanner = new Scanner(System.in);
        GrupoNuevo panta = new GrupoNuevo(this,escuelaDAO);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_NuevaClaseActionPerformed

    private void EliminarClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarClaseActionPerformed
        // TODO add your handling code here:
        EscuelaDAO escuelaDAO = new EscuelaDAO();
        GrupoDAO grupoDAO = new GrupoDAO();
        Scanner scanner = new Scanner(System.in);
        EliminarGrupo panta = new EliminarGrupo(this,escuelaDAO,grupoDAO);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }//GEN-LAST:event_EliminarClaseActionPerformed

    private void SiguienteClaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SiguienteClaseActionPerformed
       // Verifica que una escuela esté seleccionada
    String escuelaSeleccionada = ListadeEscuelas.getSelectedValue();
    String grupoSeleccionado = ListadeClase.getSelectedValue();
    AlumnoDAO alumnoDAO = new AlumnoDAO();

    if (escuelaSeleccionada == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una escuela.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else if (grupoSeleccionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un grupo.", "Advertencia", JOptionPane.WARNING_MESSAGE);
    } else {
        // Pasa el grupo seleccionado al abrir la ventana Clase
        Clase panta = new Clase(this, escuelaDAO, grupoDAO, alumnoDAO, grupoSeleccionado);
        panta.setVisible(true);
        panta.setLocationRelativeTo(null);
    }
    }//GEN-LAST:event_SiguienteClaseActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EliminarClase;
    private javax.swing.JList<String> ListadeClase;
    private javax.swing.JList<String> ListadeEscuelas;
    private javax.swing.JButton NuevaClase;
    private javax.swing.JButton SiguienteClase;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
