/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfas;
import Interfas.PantallaDeIncio;
import Interfas.InicideClase;
import javax.swing.JFrame;
import com.mycompany.escuela.EscuelaDAO;
import com.mycompany.escuela.Escuelas;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author JOVANNI SG
 */
public class NuevaEscuela extends javax.swing.JFrame {

    /**
     * Creates new form NuevaEscuela
     */
    InicideClase pantallaPrincipale; // Referencia a la Pantalla principal
    public NuevaEscuela(InicideClase pantallas) {
        
   
        this.pantallaPrincipale = pantallas; // Se pasa la referencia a Pantalla principal
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // o HIDE_ON_CLOSE según lo que necesites
        setTitle("NuevaEscuela");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NomEscuela = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Clave = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        AguardarEscuela = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Secundaria = new javax.swing.JRadioButton();
        Primaria = new javax.swing.JRadioButton();
        Preparatoria = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("MingLiU_HKSCS-ExtB", 0, 18)); // NOI18N
        jLabel1.setText("Nueva Escuela");

        jLabel2.setText("Nombre de la Escuela: ");

        jLabel4.setText("Direccion:");

        jLabel5.setText("Clave:");

        AguardarEscuela.setBackground(new java.awt.Color(0, 0, 0));
        AguardarEscuela.setForeground(new java.awt.Color(255, 255, 255));
        AguardarEscuela.setText("Aguardar");
        AguardarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguardarEscuelaActionPerformed(evt);
            }
        });

        jLabel6.setText("Que tipo de Escuela:");

        Secundaria.setBackground(new java.awt.Color(153, 153, 153));
        Secundaria.setText("Secundaria");
        Secundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecundariaActionPerformed(evt);
            }
        });

        Primaria.setBackground(new java.awt.Color(153, 153, 153));
        Primaria.setText("Primaria");
        Primaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrimariaActionPerformed(evt);
            }
        });

        Preparatoria.setBackground(new java.awt.Color(153, 153, 153));
        Preparatoria.setText("Preparatoria");
        Preparatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreparatoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(388, 388, 388))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Direccion)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(NomEscuela)
                                        .addGap(4, 4, 4)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(Primaria)
                                .addGap(18, 18, 18)
                                .addComponent(Secundaria)
                                .addGap(18, 18, 18)
                                .addComponent(Preparatoria))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AguardarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NomEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Primaria)
                    .addComponent(Secundaria)
                    .addComponent(Preparatoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addComponent(AguardarEscuela, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AguardarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguardarEscuelaActionPerformed
    String nombre = NomEscuela.getText();
    String direccion = Direccion.getText();
    String clave = Clave.getText();

    // Validación básica
    if (nombre.isEmpty() || direccion.isEmpty() || clave.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos");
        return;
    }

    // Crear objeto Escuela
    Escuelas escuela = new Escuelas(nombre, direccion, clave);
    EscuelaDAO escuelaDAO = new EscuelaDAO();

    // Intentar guardar la escuela en la base de datos
    try {
        escuelaDAO.agregarEscuela(escuela);
        javax.swing.JOptionPane.showMessageDialog(this, "Escuela guardada exitosamente");
        dispose(); // Cierra la ventana después de guardar
    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar la escuela: " + e.getMessage());
    }
    }//GEN-LAST:event_AguardarEscuelaActionPerformed

    private void SecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecundariaActionPerformed
        if (Secundaria.isSelected()) {
            Primaria.setEnabled(false);
            Preparatoria.setEnabled(false);
        } else {
            Primaria.setEnabled(true);
            Preparatoria.setEnabled(true);
        }
    }//GEN-LAST:event_SecundariaActionPerformed

    private void PrimariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrimariaActionPerformed
        if (Primaria.isSelected()) {
            Secundaria.setEnabled(false);
            Preparatoria.setEnabled(false);
        } else {
            Secundaria.setEnabled(true);
            Preparatoria.setEnabled(true);
        }
    }//GEN-LAST:event_PrimariaActionPerformed

    private void PreparatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreparatoriaActionPerformed
        if (Preparatoria.isSelected()) {
            Primaria.setEnabled(false);
            Secundaria.setEnabled(false);
        } else {
            Primaria.setEnabled(true);
            Secundaria.setEnabled(true);
        }
    }//GEN-LAST:event_PreparatoriaActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AguardarEscuela;
    private javax.swing.JTextField Clave;
    private javax.swing.JTextField Direccion;
    private javax.swing.JTextField NomEscuela;
    private javax.swing.JRadioButton Preparatoria;
    private javax.swing.JRadioButton Primaria;
    private javax.swing.JRadioButton Secundaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
